hdfs shell

diff --git a/ubin/dtformat b/ubin/dtformat
--- a/ubin/dtformat
+++ b/ubin/dtformat
@@ -17,7 +17,9 @@ do
 	echo "$n rm dn/* ok"
 done
 
-
+ssh $m 'hdfs namenode -format -clusterID cute' &>/dev/null
+[ "$?" != "0" ] && echo "formathdfs failure" && exit 1
+echo "formathdfs ok"
 
 
 
